import api from '../api';
import { Sparkles, Brain, Clock, Target, Activity, ArrowLeft, Send, Zap } from 'lucide-react';

const AIMentor = () => {
  const navigate = useNavigate();
  const [goal, setGoal] = useState('');
  const [weeklyHours, setWeeklyHours] = useState(5);
  const [loading, setLoading] = useState(false);
  const [plan, setPlan] = useState(null);
  const [error, setError] = useState('');

  useEffect(() => {
    document.title = 'SkillSphereX • AI Mentor';
  }, []);

  const fetchPlan = async (e) => {
    e?.preventDefault();
    setError('');
    setLoading(true);

    try {
      const user = JSON.parse(localStorage.getItem('user'));
      const config = {
        headers: {
          Authorization: `Bearer ${user.token}`,
        },
      };
      const { data } = await api.post(
        '/api/ai/learning-path',
        {
          goal: goal || 'Improve my skills and employability',
          weeklyHours: Number(weeklyHours) || 5,
        },
        config
      );
      setPlan(data);
    } catch (err) {
      console.error('Error fetching AI learning plan', err);
      setError(
        err.response?.data?.message ||
        'Unable to generate a learning plan right now. Please try again.'
      );
    } finally {
      setLoading(false);
    }
  };

  const renderPlan = () => {
    if (!plan) return null;
    const { mode, plan: aiPlan, learningSnapshot } = plan;

    return (
      <div className="admin-controls" style={{ marginTop: '3rem' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '2rem' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '15px' }}>
            <div
              style={{
                width: 50,
                height: 50,
                borderRadius: '15px',
                background: 'rgba(99, 102, 241, 0.1)',
                border: '1px solid var(--primary)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                color: 'var(--primary)',
                boxShadow: '0 0 20px var(--primary-glow)'
              }}
            >
              <Brain size={24} />
            </div>
            <div>
              <h2 style={{ margin: 0, fontSize: '1.5rem' }}>Your Intelligent Roadmap</h2>
              <p style={{ margin: '0.25rem 0 0', fontSize: '0.9rem', color: 'var(--text-muted)' }}>
                {mode === 'ai'
                  ? 'Curated by SkillSphereX AI using your real-time activity and goals.'
                  : 'Generated by an on-platform mentor based on your profile.'}
              </p>
            </div>
          </div>
        </div>

        {aiPlan?.summary && (
          <div style={{ marginBottom: '2rem', padding: '1.5rem', background: 'rgba(255,255,255,0.02)', borderRadius: 'var(--radius-md)', border: '1px solid var(--glass-border)' }}>
            <p style={{ margin: 0, fontSize: '1.1rem', lineHeight: '1.7' }}>{aiPlan.summary}</p>
          </div>
        )}

        {aiPlan?.focusAreas && aiPlan.focusAreas.length > 0 && (
          <div style={{ marginBottom: '2rem' }}>
            <h4 style={{ marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '8px' }}>
              <Target size={18} className="text-primary" /> Core Focus Areas
            </h4>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '10px' }}>
              {aiPlan.focusAreas.map((item, idx) => (
                <span key={idx} style={{ padding: '0.5rem 1rem', background: 'var(--glass)', border: '1px solid var(--glass-border)', borderRadius: '50px', fontSize: '0.85rem' }}>
                  {item}
                </span>
              ))}
            </div>
          </div>
        )}

        {aiPlan?.recommendedCourses && aiPlan.recommendedCourses.length > 0 && (
          <div style={{ marginBottom: '2rem' }}>
            <h4 style={{ marginBottom: '1.25rem' }}>The Recommended Sequence</h4>
            <div className="course-grid" style={{ gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))' }}>
              {aiPlan.recommendedCourses.map((course, idx) => (
                <div key={course.id || idx} className="course-card glass-panel" style={{ padding: '1.5rem', borderLeft: '4px solid var(--primary)' }}>
                  <div style={{ fontSize: '0.75rem', fontWeight: 800, color: 'var(--primary)', marginBottom: '0.5rem', textTransform: 'uppercase' }}>
                    Phase {idx + 1}
                  </div>
                  <h3 className="course-title" style={{ fontSize: '1.1rem', marginBottom: '0.75rem' }}>
                    {course.title}
                  </h3>
                  <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', margin: 0 }}>{course.reason}</p>
                </div>
              ))}
            </div>
          </div>
        )}

        {aiPlan?.weeklySchedule && aiPlan.weeklySchedule.length > 0 && (
          <div style={{ marginBottom: '2rem' }}>
            <h4 style={{ marginBottom: '1.25rem', display: 'flex', alignItems: 'center', gap: '8px' }}>
              <Clock size={18} className="text-primary" /> 4-Week Milestone Schedule
            </h4>
            <div className="course-grid" style={{ gridTemplateColumns: 'repeat(auto-fill, minmax(240px, 1fr))' }}>
              {aiPlan.weeklySchedule.map((week) => (
                <div key={week.week} className="course-card glass-panel" style={{ padding: '1.5rem' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
                    <div style={{ fontWeight: 800, fontSize: '0.9rem' }}>Week {week.week}</div>
                    <div style={{ padding: '2px 8px', background: 'rgba(99, 102, 241, 0.1)', color: 'var(--primary)', borderRadius: '4px', fontSize: '0.7rem', fontWeight: 700 }}>
                      {week.hours} Hours
                    </div>
                  </div>
                  <ul style={{ paddingLeft: '1.25rem', fontSize: '0.85rem', color: 'var(--text-muted)', margin: 0, display: 'flex', flexDirection: 'column', gap: '8px' }}>
                    {(week.activities || []).map((act, idx) => (
                      <li key={idx}>{act}</li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>
        )}

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '2rem' }}>
          {aiPlan?.quizStrategy && aiPlan.quizStrategy.length > 0 && (
            <div className="glass-panel" style={{ padding: '1.5rem', borderRadius: 'var(--radius-md)' }}>
              <h4 style={{ marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '8px' }}>
                <Activity size={18} className="text-secondary" /> Assessment Strategy
              </h4>
              <ul style={{ paddingLeft: '1.25rem', color: 'var(--text-muted)', fontSize: '0.9rem', margin: 0, display: 'flex', flexDirection: 'column', gap: '8px' }}>
                {aiPlan.quizStrategy.map((item, idx) => (
                  <li key={idx}>{item}</li>
                ))}
              </ul>
            </div>
          )}

          {aiPlan?.motivationTips && aiPlan.motivationTips.length > 0 && (
            <div
              className="glass-panel"
              style={{
                padding: '1.5rem',
                borderRadius: 'var(--radius-md)',
                border: '1px solid rgba(16, 185, 129, 0.2)',
                background: 'rgba(16, 185, 129, 0.02)'
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '1rem', color: 'var(--success)' }}>
                <Zap size={18} />
                <h4 style={{ margin: 0, color: 'var(--success)' }}>AI Motivation Tips</h4>
              </div>
              <ul style={{ paddingLeft: '1.25rem', margin: 0, fontSize: '0.9rem', color: 'var(--text-muted)', display: 'flex', flexDirection: 'column', gap: '8px' }}>
                {aiPlan.motivationTips.map((tip, idx) => (
                  <li key={idx}>{tip}</li>
                ))}
              </ul>
            </div>
          )}
        </div>

        {learningSnapshot && (
          <details style={{ marginTop: '2.5rem', fontSize: '0.8rem', color: 'var(--text-muted)' }}>
            <summary style={{ cursor: 'pointer', fontWeight: 600 }}>Inspect logic behind this plan</summary>
            <pre style={{ marginTop: '1rem', maxHeight: 300, overflow: 'auto', background: 'rgba(15, 23, 42, 0.8)', color: '#e5e7eb', padding: '1.5rem', borderRadius: 'var(--radius-md)', border: '1px solid var(--glass-border)', fontSize: '0.75rem' }}>
              {JSON.stringify(learningSnapshot, null, 2)}
            </pre>
          </details>
        )}
      </div>
    );
  };

  return (
    <div className="admin-panel">
      <div style={{ display: 'flex', gap: '1.5rem', alignItems: 'center', marginBottom: '2.5rem' }}>
        <button onClick={() => navigate('/dashboard')} className="btn btn-secondary" style={{ width: 'auto' }}>
          <ArrowLeft size={18} /> Back to Dashboard
        </button>
        <div style={{ flex: 1 }}>
          <h1 className="section-title" style={{ marginBottom: '0.5rem' }}>
            AI Personal Skill Mentor
          </h1>
          <p style={{ color: 'var(--text-muted)', margin: 0 }}>
            Dynamic, data-driven learning roadmaps generated from your unique progress.
          </p>
        </div>
        <div
          style={{
            padding: '0.6rem 1.25rem',
            borderRadius: '999px',
            background: 'var(--card-bg)',
            border: '1px solid var(--primary)',
            display: 'flex',
            alignItems: 'center',
            gap: '8px',
            color: 'var(--primary)',
            boxShadow: '0 0 15px var(--primary-glow)'
          }}
        >
          <Sparkles size={16} />
          <span style={{ fontSize: '0.8rem', fontWeight: 800, textTransform: 'uppercase', letterSpacing: '0.05em' }}>AI Engine Active</span>
        </div>
      </div>

      <div style={{ display: 'flex', justifyContent: 'center', marginTop: '1rem' }}>
        <div className="admin-controls" style={{ width: '100%', maxWidth: '800px', position: 'relative', overflow: 'hidden' }}>
          {/* Background decoration */}
          <div style={{ position: 'absolute', top: '-100px', right: '-100px', width: '200px', height: '200px', background: 'var(--primary-glow)', filter: 'blur(80px)', borderRadius: '50%', opacity: 0.3, pointerEvents: 'none' }}></div>

          <div style={{ position: 'relative', zIndex: 1 }}>
            <h3 style={{ marginTop: 0, fontSize: '1.5rem', marginBottom: '1.5rem' }}>Configure Your Mentor</h3>

            {error && (
              <div className="error-message">
                {error}
              </div>
            )}

            <form onSubmit={fetchPlan}>
              <div className="form-group">
                <label style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <Target size={16} className="text-primary" /> What is your primary learning goal?
                </label>
                <textarea
                  value={goal}
                  onChange={(e) => setGoal(e.target.value)}
                  rows={4}
                  className="input"
                  placeholder="Examples: 'Master React & Node.js', 'Clear my upcoming DSA interview', 'Begin my journey in Cyber Security'..."
                  style={{
                    width: '100%',
                    background: 'rgba(15, 23, 42, 0.4)',
                    border: '1px solid var(--glass-border)',
                    resize: 'none'
                  }}
                />
              </div>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '2rem' }}>
                <div className="form-group">
                  <label style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                    <Clock size={16} className="text-primary" /> Weekly Study Capacity
                  </label>
                  <div style={{ position: 'relative' }}>
                    <input
                      type="number"
                      min="1"
                      max="100"
                      value={weeklyHours}
                      onChange={(e) => setWeeklyHours(e.target.value)}
                      className="input"
                      style={{ width: '100%', paddingRight: '4rem' }}
                    />
                    <span style={{ position: 'absolute', right: '1rem', top: '50%', transform: 'translateY(-50%)', color: 'var(--text-muted)', fontSize: '0.9rem' }}>Hours</span>
                  </div>
                </div>

                <div style={{ display: 'flex', alignItems: 'flex-end', paddingBottom: '1.5rem' }}>
                  <button
                    type="submit"
                    className="btn"
                    style={{
                      width: '100%',
                      height: '3.3rem',
                      background: 'linear-gradient(135deg, var(--primary) 0%, var(--secondary) 100%)',
                      boxShadow: '0 4px 15px var(--primary-glow)'
                    }}
                    disabled={loading}
                  >
                    {loading ? (
                      <>Processing Logic...</>
                    ) : (
                      <><Send size={18} /> Generate Intelligent Plan</>
                    )}
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>

      {renderPlan()}
    </div>
  );
};

export default AIMentor;
